<?php

// autoload_classmap.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'FacebookApiException' => $baseDir . '/vendors/facebook/php-sdk/src/base_facebook.php',
    'BaseFacebook' => $baseDir . '/vendors/facebook/php-sdk/src/base_facebook.php',
    'Facebook' => $baseDir . '/vendors/facebook/php-sdk/src/facebook.php',
);
